package tests;// Generated by Selenium IDE

import base.TestBase;
import dto.Account;
import generator.DataGenerator;
import org.junit.Assert;

public class CorrectLoginTest extends TestBase {
    private Account testAccount;

    @Override
    public void additionalSetup() {
        testAccount = DataGenerator.readAccount("account.json");
    }

    @Override
    public void testCase() {
        if (app.auth().isLoggedIn()) {
            app.auth().logout();
        }
        while (!app.auth().isLoggedIn()) {
            app.navigation().navigateTo("/");
            app.auth().authWith(testAccount);
        }
        app.navigation().navigateTo("/app");

        Assert.assertEquals(testAccount.getEmail(), app.auth().authenticatedEmail());
    }
}
