package tests;// Generated by Selenium IDE

import base.TestBase;
import dto.Account;
import dto.Note;
import generator.DataGenerator;
import org.junit.Assert;

public class CreateEntityTest extends TestBase {

    private Account testAccount;
    private Note testNote;

    @Override
    public void additionalSetup() {
        testAccount = DataGenerator.readAccount("account.json");
        testNote = DataGenerator.readNote("note.json");
    }
    @Override
    public void testCase() {
        // auth

        app.window().resize(928, 694);
        app.navigation().navigateTo("/");
        app.auth().authWith(testAccount);

        // entity creation
        app.navigation().navigateTo("/app");
        app.note().newWith(testNote);
        Note createdNote = app.note().lastCreatedNote();

        Assert.assertEquals(testNote.getContent(), createdNote.getContent());

        app.auth().logout();
    }
}
