package tests;// Generated by Selenium IDE

import base.TestBase;
import dto.Account;
import dto.Note;

public class CreateEntityTest extends TestBase {
    @Override
    public void testCase() {
        // login
        Account testAccount = new Account("yajanah653@glenwoodave.com", "qwerty123");

        app.window().resize(928, 694);
        app.navigation().navigateTo("/");
        app.login().authWith(testAccount);

        // entity creation
        Note testNote = new Note("Sample Text");
        app.navigation().navigateTo("/app");
        app.note().newWith(testNote);
    }
}
