package tests;// Generated by Selenium IDE

import base.TestBase;
import dto.Account;
import org.junit.Assert;

public class LoginTest extends TestBase {
    @Override
    public void testCase() {
        Account testAccount = new Account("yajanah653@glenwoodave.com", "qwerty123");

        app.window().resize(928, 694);
        app.navigation().navigateTo("/");
        app.auth().authWith(testAccount);
        app.navigation().navigateTo("/app");

        Assert.assertEquals(testAccount.getEmail(), app.auth().authenticatedEmail());

        app.auth().logout();
    }
}
