package tests;// Generated by Selenium IDE

import base.TestBase;
import dto.Account;
import generator.DataGenerator;
import org.junit.Assert;

public class LoginTest extends TestBase {
    private Account testAccount;

    @Override
    public void additionalSetup() {
        testAccount = DataGenerator.readAccount("account.json");
    }

    @Override
    public void testCase() {
        app.window().resize(928, 694);
        app.navigation().navigateTo("/");
        app.auth().authWith(testAccount);
        app.navigation().navigateTo("/app");

        Assert.assertEquals(testAccount.getEmail(), app.auth().authenticatedEmail());

        app.auth().logout();
    }
}
